# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=10)),
                ('bpub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='heros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
